import os
import pandas as pd
import numpy as np

def calculate_rsi(series, period=14):
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_macd(series, short_period=12, long_period=26, signal_period=9):
    ema_short = series.ewm(span=short_period, adjust=False).mean()
    ema_long = series.ewm(span=long_period, adjust=False).mean()
    macd = ema_short - ema_long
    signal = macd.ewm(span=signal_period, adjust=False).mean()
    return macd, signal

def process_mtf_data(input_path: str, output_path: str):
    print(f"Processing MTF data from {input_path}")
    df = pd.read_parquet(input_path)
    
    # Identify unique prefixes representing different timeframes
    # E.g. base has no prefix or we can assume base columns are 'open', 'close', etc.
    # Higher timeframes have '4h_open', '1d_open', etc.
    
    all_feature_cols = []
    
    # Process base timeframe first
    base_cols = ['open', 'high', 'low', 'close', 'volume']
    if all(c in df.columns for c in base_cols):
        prefix = ""
        
        df['returns'] = df['close'].pct_change()
        df['log_returns'] = np.log(df['close'] / df['close'].shift(1))
        df['volatility_20'] = df['returns'].rolling(window=20).std()
        df['rsi_14'] = calculate_rsi(df['close'], period=14)
        df['macd'], df['macd_signal'] = calculate_macd(df['close'])
        df['macd_hist'] = df['macd'] - df['macd_signal']
        df['sma_20'] = df['close'].rolling(window=20).mean()
        df['sma_50'] = df['close'].rolling(window=50).mean()
        df['dist_sma_20'] = (df['close'] - df['sma_20']) / df['sma_20']
        df['dist_sma_50'] = (df['close'] - df['sma_50']) / df['sma_50']
        
        all_feature_cols.extend([
            'returns', 'log_returns', 'volatility_20', 'rsi_14',
            'macd', 'macd_signal', 'macd_hist', 'dist_sma_20', 'dist_sma_50'
        ])

    # Find unique prefixes (e.g., '4h_', '1d_')
    prefixes = set()
    for col in df.columns:
        if '_' in col and (col.endswith('_close') or col.endswith('_open')):
            parts = col.split('_')
            prefixes.add(parts[0] + "_")

    for pfx in prefixes:
        close_col = f"{pfx}close"
        if close_col not in df.columns:
            continue
            
        df[f'{pfx}returns'] = df[close_col].pct_change()
        df[f'{pfx}log_returns'] = np.log(df[close_col] / df[close_col].shift(1))
        df[f'{pfx}volatility_20'] = df[f'{pfx}returns'].rolling(window=20).std()
        df[f'{pfx}rsi_14'] = calculate_rsi(df[close_col], period=14)
        df[f'{pfx}macd'], df[f'{pfx}macd_signal'] = calculate_macd(df[close_col])
        df[f'{pfx}macd_hist'] = df[f'{pfx}macd'] - df[f'{pfx}macd_signal']
        df[f'{pfx}sma_20'] = df[close_col].rolling(window=20).mean()
        df[f'{pfx}sma_50'] = df[close_col].rolling(window=50).mean()
        df[f'{pfx}dist_sma_20'] = (df[close_col] - df[f'{pfx}sma_20']) / df[f'{pfx}sma_20']
        df[f'{pfx}dist_sma_50'] = (df[close_col] - df[f'{pfx}sma_50']) / df[f'{pfx}sma_50']
        
        all_feature_cols.extend([
            f'{pfx}returns', f'{pfx}log_returns', f'{pfx}volatility_20', f'{pfx}rsi_14',
            f'{pfx}macd', f'{pfx}macd_signal', f'{pfx}macd_hist', f'{pfx}dist_sma_20', f'{pfx}dist_sma_50'
        ])
    
    # Drop NaNs generated by rolling windows
    df = df.dropna()
    
    # Normalize features
    features_mean = df[all_feature_cols].mean()
    features_std = df[all_feature_cols].std()
    
    df_normalized = df.copy()
    
    # Avoid division by zero
    features_std = features_std.replace(0, 1)
    df_normalized[all_feature_cols] = (df[all_feature_cols] - features_mean) / features_std
    
    # Save processed dataframe
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df_normalized.to_parquet(output_path)
    print(f"Saved processed MTF data to {output_path}")
    print(f"Generated {len(all_feature_cols)} features.")
    
if __name__ == "__main__":
    raw_mtf_path = "data/processed/BTCUSDT_1h_MTF_raw.parquet"
    if not os.path.exists(raw_mtf_path):
        print(f"Error: {raw_mtf_path} not found. Run mtf_aligner.py first.")
    else:
        output_path = "data/processed/BTCUSDT_1h_MTF_features.parquet"
        process_mtf_data(raw_mtf_path, output_path)
